version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: imsu_postgres
    environment:
      POSTGRES_USER: imsuv3user
      POSTGRES_PASSWORD: anaevu1
      POSTGRES_DB: imsu_v3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 